services:
  api:
    container_name: conversational_recommender_system
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
    ports:
      - 8001:8001
    volumes:
      - .:/app
